### ISSUE TITLE
Possible to have non-publisher for RPC method parameter?

### ISSUE THREAD

**Issue by deepak-auto** [salesforce/reactive-grpc#295] opened 2022-06-14 14:12 UTC
Using the example in the README, can we have this method signature
```
ReactorGreeterGrpc.GreeterImplBase svc = new ReactorGreeterGrpc.GreeterImplBase() {
    @Override
    public Mono<HelloResponse> sayHello(HelloRequest request) {
        return greet("Hello", request);
    }
};
```
instead of 
```
ReactorGreeterGrpc.GreeterImplBase svc = new ReactorGreeterGrpc.GreeterImplBase() {
    @Override
    public Mono<HelloResponse> sayHello(Mono<HelloRequest> request) {
        return request.map(protoRequest -> greet("Hello", protoRequest));
    }
};
``` 
?

This way, we can access the `request` object from anywhere in the method. It will prevent us from writing an extra `map` function as in the example above.

**Comment by bsideup** [comment] 2022-11-24 23:18
Duplicate of https://github.com/salesforce/reactive-grpc/issues/78 (shouldn't be closed, btw :))

**Comment by bsideup** [comment] 2022-11-24 23:58
Have submitted https://github.com/salesforce/reactive-grpc/pull/301 (better later then never, huh? 😄)

**Closed** 2023-04-10 16:34 UTC
