### ISSUE TITLE
Backpressure Demo has sporadic exception

### ISSUE THREAD

**Issue by frankbenoit** [salesforce/reactive-grpc#162] opened 2019-03-24 07:14 UTC
Hi

Sometime starting the demo, i get this message:
````
io.reactivex.exceptions.MissingBackpressureException: Can't deliver value 128 due to lack of requests
````

in the demo, I modified the onError from System.err.println to Throwable::printStacktrace.
````
io.reactivex.exceptions.MissingBackpressureException: Can't deliver value 128 due to lack of requests
	at io.reactivex.internal.operators.flowable.FlowableInterval$IntervalSubscriber.run(FlowableInterval.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
````

Adding the onBackpressureDrop() in this line seems to fix it. Is it correct?
````
.zipWith(Flowable.interval(3, TimeUnit.MILLISECONDS), (item, interval) -> item)
.zipWith(Flowable.interval(3, TimeUnit.MILLISECONDS).onBackpressureDrop(), (item, interval) -> item)
````

Frank

**Comment by rmichela** [comment] 2019-03-25 04:03
@OlegDokuka Any ideas?

**Comment by rmichela** [comment] 2019-04-03 04:18
Demos are still using 0.9.0. I tested with 0.10.0-RC1 and couldn't reproduce. Will update demos POMs and keep trying to reproduce.

**Comment by rmichela** [comment] 2019-05-04 05:30
I believe this is fixed in 0.10.0

**Closed by rmichela** 2019-05-04 05:30 UTC
Labels: bug
