### ISSUE TITLE
Reactor Plugin Doesn't Generate Stub On Recent Versions

### ISSUE THREAD

**Issue by san4d** [salesforce/reactive-grpc#239] opened 2021-05-26 16:31 UTC
# Summary
On a minimal project using the `reactor-grpc` plugin, there is a compile issue caused by a missing stub class. 

```text
[ERROR] ... test-reactive-grpc/target/generated-sources/protobuf/java/com/example/Greeter/ReactorGreeterGrpc.java:[21,28] cannot find symbol
[ERROR]   symbol:   class GreeterStub
[ERROR]   location: class com.example.Greeter.GreeterGrpc
[ERROR] ... test-reactive-grpc/target/generated-sources/protobuf/java/com/example/Greeter/ReactorGreeterGrpc.java:[3,1] cannot find symbol
```

| Java  |  protoc | reactor-grpc | protoc-gen-grpc-java | protobuf-maven-plugin |
| ----- | ------- | ------------- | ----------------------| ----------------------- |
|  11.0.11 |  3.17.1 |  1.0.1 |  1.38.0 | 0.6.1 |

# Reproducing the Issue
Create a simple Maven project with the protobuf definition and pom below. Then, attempt to compile the application:
```bash
mvn clean compile
```

## Protobuf 
```proto
syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.example.Greeter";
option java_outer_classname = "GreeterGrpc";
option objc_class_prefix = "GTR";

service Greeter {
    rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
    string name = 1;
}

message HelloReply {
    string message = 1;
}
```
## Pom
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>test-reactive-grpc</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <protoc.version>3.17.1</protoc.version>
        <reactor-grpc-stub.version>1.0.1</reactor-grpc-stub.version>
        <protoc-gen-grpc-java.version>1.38.0</protoc-gen-grpc-java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>${protoc.version}</version>
        </dependency>
        <dependency>
            <groupId>com.salesforce.servicelibs</groupId>
            <artifactId>reactor-grpc-stub</artifactId>
            <version>${reactor-grpc-stub.version}</version>
        </dependency>
    </dependencies>

    <build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.6.0</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.6.1</version>
                <configuration>
                    <protocArtifact>
                        com.google.protobuf:protoc:${protoc.version}:exe:${os.detected.classifier}
                    </protocArtifact>
                    <pluginArtifact>
                        io.grpc:protoc-gen-grpc-java:${protoc-gen-grpc-java.version}:exe:${os.detected.classifier}
                    </pluginArtifact>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>test-compile</goal>
                        </goals>
                        <configuration>
                            <protocPlugins>
                                <protocPlugin>
                                    <id>reactor-grpc</id>
                                    <groupId>com.salesforce.servicelibs</groupId>
                                    <artifactId>reactor-grpc</artifactId>
                                    <version>${reactor-grpc-stub.version}</version>
                                    <mainClass>com.salesforce.reactorgrpc.ReactorGrpcGenerator</mainClass>
                                </protocPlugin>
                            </protocPlugins>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

# Attempts
At first, I thought it might have been related to https://github.com/salesforce/reactive-grpc/issues/213. The resolution there had to do with ensuring the `reactor-grpc` was not included as a direct dependency. Since I don't have it as a dependency, I tried downgrading to the versions mentioned in the MR and found the same result. I've also tried bringing in various dependencies on `io.grpc` to troubleshoot. 

If we get this issue resolved, I'd be happy to document and contribute a minimal working example somewhere in this repository.

**Comment by rmichela** [comment] 2021-05-26 18:19
It's possible the Reactor team issued a breaking change again. They have no problem introducing incompatible changes without warning.

**Comment by san4d** [comment] 2021-05-26 19:18
I just tried with RxJava and see the same exact error.  I feel like that's strong evidence it's related to the `org.xolstice.maven.plugins` integration.

**Comment by rmichela** [comment] 2021-06-28 15:24
What is your os/platform?

**Comment by rmichela** [comment] 2022-01-23 20:27
Not reproducible - closing

**Closed by rmichela** 2022-01-23 20:27 UTC
Labels: bug, reactor

**Comment by norbertwnuk** [comment] 2023-04-23 19:18
I have encountered similar issue myself, it turned out that the example above has 2 misconfigurations:
- invalid goal definition
```
# original lines
<goals>
    <goal>compile</goal>
    <goal>test-compile</goal>
</goals>
# after correction
<goals>
    <goal>compile</goal>
    <goal>compile-custom</goal>
</goals>
```
- invalid proto definition
```
# original lines
option java_package = "com.example.Greeter";
option java_outer_classname = "GreeterGrpc";
# after correction
option java_package = "com.example";
option java_outer_classname = "GreeterProto";
```
Generally documentation is kind of misleading, since `protocPlugins` is actually participating in ```compile``` goal, not ```compile-custom```, it easily visible on the screenshot below and important for those who has separate execution for each goal.

![image](https://user-images.githubusercontent.com/70071/233860107-86808ff0-facd-40ad-81e6-e7cfddc80a8a.png)


Lastly, I was comparing the example above with the [hello world](https://github.com/salesforce/reactive-grpc/tree/master/demos/hello-world) sample that per se works, except it does not compile due to missing dependency - as far I see examples are not a part of CI.
